name: Deploy Node.js app

on:
  push:
    branches:
      - pratiksha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-express-app .

      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push my-express-app

      - name: Deploy app via SSH
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} username@your-server-ip 'docker pull my-express-app && docker run -d -p 80:80 my-express-app'
